---
# tasks file for fileCreation
     - name: Create Chef-dev directory
       file:
         path: /{{ CHEF_DIR }}/{{ item }}
         state: directory
       with_items:
        - cookbooks
        - environments
     - name: creating cookbook folder
       file:
        path: /{{ CHEF_DIR }}/cookbooks/{{ COOKBOOK_NAME }}
        state: directory
     - name: Downloading cookbook packge from GIT Repo
       git:
         repo: {{ COOKBOOK_GIT_LOCATION }}
         dest: /{{ CHEF_DIR }}/cookbooks/{{ COOKBOOK_NAME }}
     - name: copying solo.rb and startup.json
       template:
         src: "{{ item.src }}"
         dest: "/{{ CHEF_DIR }}/{{ item.dest }}"
       with_items:
        - { src: templates/solo_template.rb.j2, dest: solo.rb }
        - { src: templates/startup.json.j2, dest: startup.json }
     - name:  copy env_template to chef env folder
       template:
         src: templates/env_template.rb.j2
         dest: /{{ CHEF_DIR }}/environments/{{ CHEF_ENV_DETAIL }}.rb
     - name: Invoke Chef-client on remote node
       shell: "{{ CHEF_CMD_TO_INVOKE_COOKBOOK }}"
