---
# vars file for fileCreation

CHEF_CMD_TO_INVOKE_COOKBOOK: " chef-solo -c /{{ CHEF_DIR }}/solo.rb -j /{{ CHEF_DIR }}/startup.json -E {{ CHEF_ENV_DETAIL }} "
CHEF_DIR: chef-cookbook-install
COOKBOOK_GIT_LOCATION: 'https://github.com/muralidharansomasundaram/{{ COOKBOOK_NAME }}.git'
